# .goreleaser.yml

# The lines below are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

before:
  hooks:
    - go mod tidy

builds:
  - ldflags:
      - -s -w -X gitfab/src.Version={{.Version}}
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - "386"
      - amd64
      - arm64
    goarm:
      - "7"
    ignore:
      - goarch: "386"
        goos: darwin
archives:
  - format_overrides:
      - goos: windows
        formats: [zip]

homebrew_casks:
  - name: gitfab
    repository:
      owner: JamesWoolfenden
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    commit_author:
      name: "GitHub Action"
      email: action@github.com
    homepage: "https://github.com/JamesWoolfenden/gitfab#readme"
    description: "Opens a git repo in a browser"
    hooks:
      post:
        install: |
          if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gitfab"]
          end
